const cityW = [
  "Wadi as Sir	Jordan",
  "Winejok	South Sudan",
  "Wau	South Sudan",
  "Wad Medani	Sudan",
  "Wola	Poland",
  "Wawer	Poland",
  "Warsaw	Poland",
  "Witbank	South Africa",
  "Westonaria	South Africa",
  "Welkom	South Africa",
  "Warmbaths	South Africa",
  "Wazirabad	Pakistan",
  "Wokha	India",
  "Washim	India",
  "Wardha	India",
  "Warangal	India",
  "Wanparti	India",
  "Wani	India",
  "Wusu	China",
  "Wonosobo	Indonesia",
  "Weru	Indonesia",
  "Weleri	Indonesia",
  "Wedi	Indonesia",
  "Watampone	Indonesia",
  "Wulingyuan	China",
  "Wacheng	China",
  "Wenxing	China",
  "Wuzhou	China",
  "Wuzhen	China",
  "Wuyang	China",
  "Wuxue	China",
  "Wushan	China",
  "Wuxi	China",
  "Wushan	China",
  "Wujing	China",
  "Wuhu	China",
  "Wuhan	China",
  "Wuhai	China",
  "Wugang	China",
  "Wuda	China",
  "Wucheng	China",
  "Wenzhou	China",
  "Wenshang	China",
  "Wenling	China",
  "Wenjiang	China",
  "Wenchang	China",
  "Weinan	China",
  "Weimiao	China",
  "Weihai	China",
  "Weifang	China",
  "Wayaobu	China",
  "Wanxian	China",
  "Wanning	China",
  "Wangji	China",
  "Wafangdian	China",
  "Wuxi	China",
  "Wuchuan	China",
  "Wuwei	China",
  "Weining	China",
  "Wonju	South Korea",
  "Wanju	South Korea",
  "Wonsan	North Korea",
  "Woodlands	Singapore",
  "Wako	Japan",
  "Wabu	South Korea",
  "Wuzhishan	China",
  "Wuyishan	China",
  "Wakayama	Japan",
  "Wuchang	China",
  "Wangqing	China",
  "Wangkui	China",
  "Wollongong	Australia",
  "Wellington	New Zealand",
  "Wum	Cameroon",
  "Wa	Ghana",
  "Wukari	Nigeria",
  "Warri	Nigeria",
  "Waterloo	Sierra Leone",
  "Winterthur	Switzerland",
  "Woluwe-Saint-Lambert	Belgium",
  "Wuerzburg	Germany",
  "Wuppertal	Germany",
  "Worms	Germany",
  "Wolfsburg	Germany",
  "Wolfenbuettel	Germany",
  "Witten	Germany",
  "Winterhude	Germany",
  "Wilmersdorf Bezirk	Germany",
  "Willich	Germany",
  "Wilhelmshaven	Germany",
  "Wiesbaden	Germany",
  "Wetzlar	Germany",
  "Wesel	Germany",
  "Weimar	Germany",
  "Wedding Bezirk	Germany",
  "Waiblingen	Germany",
  "Wandsbek	Germany",
  "Wroclaw	Poland",
  "Wloclawek	Poland",
  "Walbrzych	Poland",
  "Windhoek	Namibia",
  "Worcester	South Africa",
  "Wellington	South Africa",
  "Walvis Bay	Namibia",
  "Willemstad	Curacao",
  "Washington	United States",
  "Wilmington	United States",
  "Wellington	United States",
  "West Hollywood	United States",
  "West Palm Beach	United States",
  "Weston	United States",
  "Warner Robins	United States",
  "Wichita	United States",
  "Waldorf	United States",
  "West Gulfport	United States",
  "West Raleigh	United States",
  "Wilmington	United States",
  "Winston-Salem	United States",
  "Waco	United States",
  "Wichita Falls	United States",
  "West Lynchburg	United States",
  "Waterbury	United States",
  "West Hartford	United States",
  "West Haven	United States",
  "Waterloo	United States",
  "West Des Moines	United States",
  "Waukegan	United States",
  "West Ridge	United States",
  "West Town	United States",
  "Wheaton	United States",
  "Waltham	United States",
  "Weymouth	United States",
  "Worcester	United States",
  "Warren	United States",
  "Waterford	United States",
  "Westland	United States",
  "Wyoming	United States",
  "West Coon Rapids	United States",
  "Woodbury	United States",
  "Wayne	United States",
  "West New York	United States",
  "Wakefield	United States",
  "Washington Heights	United States",
  "West Albany	United States",
  "White Plains	United States",
  "Warwick	United States",
  "Waukesha	United States",
  "West Allis	United States",
  "Walnut Creek	United States",
  "Watsonville	United States",
  "West Covina	United States",
  "West Sacramento	United States",
  "Westminster	United States",
  "Whittier	United States",
  "Woodland	United States",
  "Woodland Hills	United States",
  "Westminster	United States",
  "West Jordan	United States",
  "West Valley City	United States",
  "Waterloo	Canada",
  "Welland	Canada",
  "White Rock	Canada",
  "Windsor	Canada",
  "Winnipeg	Canada",
  "Woburn	Canada",
  "Whangarei	New Zealand",
  "West Bloomfield Township	United States",
  "West Jerusalem	Israel",
  "Wenshan City	China",
  "Willowdale	Canada",
  "Waterfront Communities-The Island	Canada",
  "Willowdale East	Canada",
  "Wanchaq	Peru",
  "Wanggou	China",
  "Wanzhou	China",
];

const cityX = [
  "Xi’an	China",
  "Xiamen	China",
  "Xining	China",
  "Xiangyang	China",
  "Xuchang	China",
  "Xuzhou	China",
  "Xinyang	China",
  "Xinxiang	China",
  "Xianyang	China",
  "Xiangtan	China",
  "Xiaogan	China",
  "Xinyu	China",
  "Xingtai	China",
  "Xuanzhou	China",
  "Xinzhou	China",
  "Xianning	China",
  "Xichang	China",
  "Xalapa de Enriquez	Mexico",
  "Xochimilco	Mexico",
  "Xuanhua	China",
  "Xico	Mexico",
  "Xingyi	China",
  "Xinyi	China",
  "Xiuying	China",
  "Xinyuan	China",
  "Xingning	China",
  "Xiantao	China",
  "Xintai	China",
  "Xindi	China",
  "Xinji	China",
  "Xai-Xai	Mozambique",
  "Xiaogang	China",
  "Xiazhen	China",
  "Xiulin	China",
  "Xiangcheng	China",
  "Xilin Hot	China",
  "Xunchang	China",
  "Xigang	China",
  "Xuyong	China",
  "Xinghua	China",
  "Xiangjiaba	China",
  "Xinzhai	China",
  "Xixiang	China",
  "Xinle	China",
  "Xingcheng	China",
  "Xinshi	China",
  "Xinyi	China",
  "Xishan	China",
  "Xinxing	China",
  "Xiaoshan	China",
  "Xingguo	China",
  "Ximeicun	China",
  "Xingren	China",
  "Xihe	China",
  "Xiazhuang	China",
  "Xiangxiang	China",
  "Xujiang	China",
  "Xiannue	China",
  "Xucheng	China",
  "Xindian	China",
  "Xiugu	China",
  "Xichang	China",
  "Xiongzhou	China",
  "Xinzhou	China",
  "Xinmin	China",
  "Xianshuigu	China",
  "Xinzhi	China",
  "Xiuyan	China",
  "Xinhe	China",
  "Xuantan	China",
  "Xiaoshi	China",
  "Xunyang	China",
  "Xinzhou	China",
  "Xiaolingwei	China",
  "Xiangcheng Chengguanzhen	China",
  "Xincheng	China",
  "Xiazhuang	China",
  "Xiangzhou	China",
  "Xianju	China",
  "Xifeng	China",
  "Xiema	China",
  "Xixiang	China",
  "Xiaoweizhai	China",
  "Xinglongshan	China",
  "Xuzhuang	China",
  "Xiva	Uzbekistan",
  "Xinqing	China",
  "Xiazhuang	China",
  "Xankandi	Azerbaijan",
  "Xo`jayli Shahri	Uzbekistan",
  "Xaffevillers France",
  "Xaintrailles France",
  "Xaintray France",
  "Xambes France",
  "Xammes France",
  "Xanrey France",
  "Xanton-Chassenon France",
  "Xaronval France",
  "Xermaménil France",
  "Xertigny France",
  "Xeuilley France",
  "Xirocourt France",
  "Xivry-Circourt France",
  "Xoccourt France",
];

const countriesStartingWithB = [
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunéi Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
];

const countriesStartingWithC = [
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "République centrafricaine",
  "Tchad",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "Îles Cook",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Curaçao",
  "Chypre du Nord",
];

let cityForW = cityW[Math.floor(Math.random() * cityW.length)];

let cityForX = cityX[Math.floor(Math.random() * cityX.length)];

let countryBForAnna =
  countriesStartingWithB[
    Math.floor(Math.random() * countriesStartingWithB.length)
  ];

let countryCForAnna =
  countriesStartingWithC[
    Math.floor(Math.random() * countriesStartingWithC.length)
  ];

const cityWBox = document.getElementById("city-w");
cityWBox.innerHTML = `A city starting with W is ${cityForW}`;

const cityXBox = document.getElementById("city-x");
cityXBox.innerHTML = `A city starting with X is ${cityForX} `;

const anna2ndCountry = document.getElementById("anna-b");
anna2ndCountry.innerHTML = `Your second country is ${countryBForAnna}`;

const anna3rdCountry = document.getElementById("anna-c");
anna3rdCountry.innerHTML = `Your third country is ${countryCForAnna}`;

showContent = () => {
  document.querySelector("button").style.display = "none";
  document.querySelector("header").style.display = "none";
  document.querySelector("#content").style.display = "block";
};
