const cityX = [
  "Xi’an	China",
  "Xiamen	China",
  "Xining	China",
  "Xiangyang	China",
  "Xuchang	China",
  "Xuzhou	China",
  "Xinyang	China",
  "Xinxiang	China",
  "Xianyang	China",
  "Xiangtan	China",
  "Xiaogan	China",
  "Xinyu	China",
  "Xingtai	China",
  "Xuanzhou	China",
  "Xinzhou	China",
  "Xianning	China",
  "Xichang	China",
  "Xalapa de Enriquez	Mexico",
  "Xochimilco	Mexico",
  "Xuanhua	China",
  "Xico	Mexico",
  "Xingyi	China",
  "Xinyi	China",
  "Xiuying	China",
  "Xinyuan	China",
  "Xingning	China",
  "Xiantao	China",
  "Xintai	China",
  "Xindi	China",
  "Xinji	China",
  "Xai-Xai	Mozambique",
  "Xiaogang	China",
  "Xiazhen	China",
  "Xiulin	China",
  "Xiangcheng	China",
  "Xilin Hot	China",
  "Xunchang	China",
  "Xigang	China",
  "Xuyong	China",
  "Xinghua	China",
  "Xiangjiaba	China",
  "Xinzhai	China",
  "Xixiang	China",
  "Xinle	China",
  "Xingcheng	China",
  "Xinshi	China",
  "Xinyi	China",
  "Xishan	China",
  "Xinxing	China",
  "Xiaoshan	China",
  "Xingguo	China",
  "Ximeicun	China",
  "Xingren	China",
  "Xihe	China",
  "Xiazhuang	China",
  "Xiangxiang	China",
  "Xujiang	China",
  "Xiannue	China",
  "Xucheng	China",
  "Xindian	China",
  "Xiugu	China",
  "Xichang	China",
  "Xiongzhou	China",
  "Xinzhou	China",
  "Xinmin	China",
  "Xianshuigu	China",
  "Xinzhi	China",
  "Xiuyan	China",
  "Xinhe	China",
  "Xuantan	China",
  "Xiaoshi	China",
  "Xunyang	China",
  "Xinzhou	China",
  "Xiaolingwei	China",
  "Xiangcheng Chengguanzhen	China",
  "Xincheng	China",
  "Xiazhuang	China",
  "Xiangzhou	China",
  "Xianju	China",
  "Xifeng	China",
  "Xiema	China",
  "Xixiang	China",
  "Xiaoweizhai	China",
  "Xinglongshan	China",
  "Xuzhuang	China",
  "Xiva	Uzbekistan",
  "Xinqing	China",
  "Xiazhuang	China",
  "Xankandi	Azerbaijan",
  "Xo`jayli Shahri	Uzbekistan",
  "Xaffevillers France",
  "Xaintrailles France",
  "Xaintray France",
  "Xambes France",
  "Xammes France",
  "Xanrey France",
  "Xanton-Chassenon France",
  "Xaronval France",
  "Xermaménil France",
  "Xertigny France",
  "Xeuilley France",
  "Xirocourt France",
  "Xivry-Circourt France",
  "Xoccourt France",
];

const countriesStartingWithB = [
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunéi Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
];

const countriesStartingWithC = [
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "République centrafricaine",
  "Tchad",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "Îles Cook",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Curaçao",
  "Chypre du Nord",
];
